FROM alpine:3.23.2 AS builder
RUN apk update
RUN apk add curl

RUN curl \
    --location \
    --fail \
    --show-error \
    --remote-name \
    https://gitlab.haskell.org/haskell-wasm/ghc-wasm-meta/-/raw/master/bootstrap.sh

RUN apk add bash
RUN apk add jq
RUN apk add zstd
RUN apk add make

RUN sh -c '. bootstrap.sh'

RUN ln -s /root/.ghc-wasm/wasm32-wasi-ghc/bin/wasm32-wasi-ghc /usr/local/bin/
RUN ln -s /root/.ghc-wasm/cabal/bin/cabal /usr/local/bin/

RUN which wasm32-wasi-ghc
RUN which cabal

RUN wasm32-wasi-ghc --version
RUN cabal --version

RUN cabal update --verbose=2

RUN ln -s /root/.ghc-wasm/wasm32-wasi-ghc/bin/wasm32-wasi-ghc /usr/local/bin/ghc
RUN ln -s /root/.ghc-wasm/wasm32-wasi-ghc/bin/wasm32-wasi-ghc-pkg /usr/local/bin/
RUN ln -s /root/.ghc-wasm/wasm32-wasi-ghc/bin/wasm32-wasi-ghc-pkg /usr/local/bin/ghc-pkg

WORKDIR /hs-path-abs2rel
COPY --link ./hs-path-abs2rel.cabal ./
RUN cabal update --verbose
RUN apk add ghc
RUN which hsc2hs
RUN cabal \
    build \
    --only-dependencies
COPY --link ./src/ ./src/
COPY --link ./app/ ./app/
COPY --link ./LICENSE ./
RUN cabal \
    build
RUN cabal \
    list-bin \
    hs-path-abs2rel \
    | fgrep -m 1 hs-path-abs2rel.wasm \
    | while read line; do \
        test -f "${line}" && cp -i "${line}" /usr/local/share/; \
    done
RUN ls -lh /usr/local/share/hs-path-abs2rel.wasm

FROM scratch
COPY --from=builder /usr/local/share/hs-path-abs2rel.wasm /

CMD ["/hs-path-abs2rel.wasm"]
